background            #0a0f1f
foreground            #cbe6ff
selection_background #1b2b4a
selection_foreground #ffffff

cursor               #00f5ff
cursor_text_color   #0a0f1f

active_border_color   #00f5ff
inactive_border_color #1b2b4a

url_color #00c8ff

color0  #05080f
color8  #1a2235

color1  #ff2a6d
color9  #ff5fa1

color2  #00ffcc
color10 #4dffdf

color3  #ffd866
color11 #ffe9a3

color4  #2f7cff
color12 #5fa8ff

color5  #9d5cff
color13 #c77dff

color6  #00f5ff
color14 #5fffff

color7  #cbe6ff
color15 #ffffff

enable_ligatures yes
bold_font auto
italic_font auto

background_opacity 0.94

scrollback_lines 5000
